# Generated by Django 4.2.15 on 2024-08-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='api.module'),
        ),
    ]
